FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y software-properties-common python-software-properties
RUN add-apt-repository -y ppa:webupd8team/java

# Install.
RUN \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential && \
  apt-get install -y byobu curl git htop man unzip vim wget

RUN wget -O - https://debian.neo4j.org/neotechnology.gpg.key > key.key 
USER root
RUN apt-key add key.key
RUN echo 'deb http://debian.neo4j.org/repo stable/' > /etc/apt/sources.list.d/neo4j.list
#RUN echo 'deb http://debian.neo4j.org/repo stable/' > /etc/apt/sources.list
RUN cat /etc/apt/sources.list.d/neo4j.list 
RUN apt-get update
RUN apt-get install -y neo4j 
RUN service neo4j start
#RUN systemctl start neo4j.service

# Set environment variables.
ENV HOME /

# Define working directory.
WORKDIR /

# Define default command.
CMD ["bash"]
