FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y software-properties-common python-software-properties
RUN add-apt-repository -y ppa:webupd8team/java

ENV DEBIAN_FRONTEND noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
#RUN dpkg-reconfigure debconf

RUN echo debconf shared/accepted-oracle-license-v1-1 select true | \
  debconf-set-selections
RUN echo debconf shared/accepted-oracle-license-v1-1 seen true | \
  debconf-set-selections

# Install.
RUN \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential && \
  apt-get install -y byobu curl git htop man unzip vim wget && \
  apt-get -y install oracle-java8-installer

RUN wget -O - https://debian.neo4j.org/neotechnology.gpg.key > key.key 
USER root
RUN apt-key add key.key
RUN echo 'deb http://debian.neo4j.org/repo stable/' > /etc/apt/sources.list.d/neo4j.list
#RUN echo 'deb http://debian.neo4j.org/repo stable/' > /etc/apt/sources.list
RUN cat /etc/apt/sources.list.d/neo4j.list 
RUN apt-get update
RUN apt-get install -y neo4j 
#RUN service neo4j start
#RUN systemctl start neo4j.service

# Set environment variables.
ENV HOME /

# Define working directory.
WORKDIR /

ADD entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/entrypoint.sh


# Define default command.
CMD ["/usr/local/bin/entrypoint.sh"]
